sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 615219Ef
  qiniu:
    oss:
      access-key: un-il79ZlRWhXxDLhE_2zoURrq9RHzuxyBaCfRAg
      secret-key: SBxwkEw3LcobCmXz3X_v6NQEwZ4_jb4qk11RDgbb
      bucket: ctrlacv
      domain: http://s9ghocypn.hb-bkt.clouddn.com

